[[OpenSWPC]]
arch = "x86_64"
git-tree-sha1 = "0c20dd18eb436e44109569ff6eed11518a7e5f29"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[OpenSWPC.download]]
    sha256 = "ed7dbc2b525cacfc7422a5ca3bd39b3a58ae53932a3d00018af3aed61ea9dd42"
    url = "https://github.com/local/releases/download/OpenSWPC-v25.5.2+0/OpenSWPC.v25.5.2.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[OpenSWPC]]
arch = "aarch64"
git-tree-sha1 = "cc478a0e787463ad765806153e4fc952b3ad2ec3"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[OpenSWPC.download]]
    sha256 = "59a336d74514854fdb272ee542ec5416d809469f5ed2eea4af043aac70c3d59e"
    url = "https://github.com/boriskaus/OpenSWPC_jll.jl/releases/download/OpenSWPC-v25.5.2+0/OpenSWPC.v25.5.2.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[OpenSWPC]]
arch = "x86_64"
git-tree-sha1 = "82459f2fc086c2f9cb4f71a9049fc1d850d666a1"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[OpenSWPC.download]]
    sha256 = "6506afb75cae2896a98ee9df719fc310926831d712f6dfebd86d396578a4c0c5"
    url = "https://github.com/boriskaus/OpenSWPC_jll.jl/releases/download/OpenSWPC-v25.5.2+0/OpenSWPC.v25.5.2.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
